---
title: R data.table的几个小技巧（二）
author: Frank
date: '2020-06-19'
slug: tips-rdatatable-2
categories: []
tags: []
output:
  blogdown::html_page:
    toc: true
---

首先再次说明一下，本系列只包括一些个人的小技巧，一些比较简单的应用就不再赘述了。

# 系列文章   
[R data.table的几个小技巧（一）](/cn/2020/06/tips-rdatatable-1)   
[R data.table的几个小技巧（二）](/cn/2020/06/tips-rdatatable-2)   

# 本期内容 

## 导入 data.table
```{r library-call, echo=TRUE,results='hide'}
library(data.table)
```
```{r callknitr, include=FALSE}
library(knitr)
```

## 创建example data
```{r exampledata}
set.seed(42)
dt <- data.table(
  A1 = sample(1:100,10),
  A2 = sample(1:100,10),
  A3 = sample(1:100,10),
  B1 = sample(1:100,10),
  B2 = sample(1:100,10),
  B3 = sample(1:100,10),
  C  = sample(1:100,10)
)
```
```{r echo=FALSE}
kable(dt)
```

### Filter多列

#### 所有列都要大于20
```{r}
# 当有NA时注意使用 na.rm = TRUE
dt[rowMeans(dt>20)==1]
```
#### 任意列>90
```{r}
# 当有NA时注意使用 na.rm = TRUE
dt[rowSums(dt>90)>0]
```
#### 所有列（除了C）> C
```{r}
dt[dt[,Reduce("&",lapply(.SD,">",C)),.SDcols = !c("C")]]
```
#### 任意列（除了C）> C
```{r}
dt[dt[,Reduce("|",lapply(.SD,">",C)),.SDcols = !c("C")]]
```


### cbind

#### Base R
```{r}
dt2 <- copy(dt)

# base R
cbind(dt,dt2)
```

#### data.table way
```{r}
setDT(unlist(list(dt,dt2),recursive = FALSE),check.names = TRUE)[]
```


### 生成多列

#### 使用set
```{r}
#注意区别于lapply使用的场景

for (i in 1:3) {
  set(dt2,j = paste0("diff","_",i),value = dt[[paste0("A",i)]] - dt[[paste0("B",i)]])
}
dt2
```
#### 使用Map
```{r include=FALSE}
dt2 <- copy(dt)
```

```{r}
A_cols <- grep("A",names(dt),value = TRUE)
B_cols <- grep("B",names(dt),value = TRUE)
new_diff_cols <- paste0("diff","_",1:3)

dt2[,(new_diff_cols) := Map("-",mget(A_cols),mget(B_cols))][]
```


